# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-12 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('place_type', models.CharField(max_length=12)),
                ('rental_type', models.CharField(max_length=20)),
                ('house_rules', models.TextField()),
                ('cancellation_policy', models.CharField(max_length=10)),
                ('amenities', models.TextField()),
                ('number_of_bedrooms', models.IntegerField(max_length=2)),
                ('number_of_bathrooms', models.IntegerField(max_length=2)),
                ('accommodates', models.IntegerField(max_length=2)),
                ('times_viewed', models.IntegerField(max_length=4)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='member.Host')),
            ],
        ),
        migrations.CreateModel(
            name='Place_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to='place_images/')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='place.Place')),
            ],
        ),
    ]
