# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-12 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='accommodates',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='place',
            name='number_of_bathrooms',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='place',
            name='number_of_bedrooms',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='place',
            name='times_viewed',
            field=models.IntegerField(),
        ),
    ]
