# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-17 18:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_auto_20171012_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place_image',
            name='image',
        ),
    ]
