# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-12 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_messages', to='member.Guest')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_messages', to='member.Host')),
            ],
        ),
    ]
